config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'

  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

# Rails.application.routes.draw do
#   get 'sessions/welcome'
#   get 'sessions/new'
#   get 'sessions/create'
#   get 'sessions/destroy'
#   get 'users/new'
#   get 'users/create'
#   get 'users/show'
#   get 'users/edit'
#   get 'users/update'
#   get 'users/destroy'
#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  helper_method :current_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def welcome
  end

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to '/login'
    end
  end

  def destroy
    session.clear
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
  end

  def edit
    if !logged_in? || !@user
      redirect_to root_path
    end
  end

  def update
    if @user
      @user.update(user_params)

      if @user.errors.any?
        render "edit"
      else
        redirect_to user_path(@user)
      end
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.erb
<% if !logged_in? %>
  <%= link_to "Login", login_path %>
  <%= link_to "Sign Up", new_user_path %>
<% else %>
  <%= link_to "Log Out", logout_path, method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Would you like to Edit your Account Details?</h1>

<%= form_with model: @user, local: true do |f| %>
  <%= f.label :email %><br>
  <%= f.email_field :email, autofocus: true %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.label :first_name %><br>
  <%= f.text_field :first_name, autofocus: true %><br>

  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>

  <%= f.submit "Confirm Changes" %>
<% end %>

app/views/users/new.html.erb
<h1>Would you like to Sign Up?</h1>

<%= form_with model: @user, local: true do |f| %>
  <%= f.label :email %><br>
  <%= f.email_field :email, autofocus: true %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.label :first_name %><br>
  <%= f.text_field :first_name, autofocus: true %><br>

  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>

  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.username %></h1>
<%= link_to "Edit Account", edit_user_path(current_user) %>
<%= link_to "Delete Account", current_user, data: { confirm: "Are you sure?" }, method: :delete %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>